CREATE TABLE IF NOT EXISTS TESTTABLE (
	FIRST_NAME  VARCHAR(20) NOT NULL,
	LAST_NAME  VARCHAR(20),
	AGE INT, 
	SEX TINYINT(1),
	INCOME DECIMAL,
	ID INT AUTO_INCREMENT PRIMARY KEY,
	CONSTRAINT ck_sex CHECK(`SEX` IN (0,1)),
	CONSTRAINT ue UNIQUE(ID)
);
CREATE TABLE IF NOT EXISTS TESTTABLE2 (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	`DATA`FLOAT,
	CONSTRAINT fr_id
	FOREIGN KEY(ID) REFERENCES TESTTABLE(ID)
);
ALTER TABLE `TESTTABLE2` DROP CONSTRAINT fr_id;
ALTER TABLE `TESTTABLE2` ADD CONSTRAINT fr_id FOREIGN KEY(ID) REFERENCES TESTTABLE(ID);
ALTER TABLE `TESTTABLE2` MODIFY COLUMN `DATA` DECIMAL NOT NULL DEFAULT 0;
alter TABLE `TESTTABLE2` ADD COLUMN `TESTCOL` DECIMAL NOT NULL UNIQUE;
alter TABLE `TESTTABLE2` CHANGE COLUMN `TESTCOL` `TESTCOL2` DECIMAL NOT NULL UNIQUE;
alter TABLE `TESTTABLE2` drop COLUMN `TESTCOL2`;
ALTER TABLE `TESTTABLE2` RENAME TO `TESTTABLE1`;

-- INSERT INTO `TESTTABLE`
-- (`FIRST_NAME`, `LAST_NAME`, `AGE`, `SEX`, `INCOME`)
-- VALUES ('Li', 'Junjie', 0, 0, 6);
-- INSERT INTO `TESTTABLE`
-- (`FIRST_NAME`, `LAST_NAME`, `AGE`, `SEX`, `INCOME`)
-- VALUES ('Li', 'Junjie', 0, 1, 3);
-- INSERT INTO `TESTTABLE`
-- (`FIRST_NAME`, `LAST_NAME`, `AGE`, `SEX`, `INCOME`)
-- VALUES ('Li', 'Junjie', 0, 0, 7);
-- INSERT INTO `TESTTABLE`
-- (`FIRST_NAME`, `LAST_NAME`, `AGE`, `SEX`, `INCOME`)
-- VALUES ('Li', 'Junjie', 0, 1, 2);
-- INSERT INTO `TESTTABLE`
-- (`FIRST_NAME`, `LAST_NAME`, `AGE`, `SEX`, `INCOME`)
-- VALUES ('Li', 'Junjie', 0, 0, 8);
-- INSERT INTO `TESTTABLE`
-- (`FIRST_NAME`, `LAST_NAME`, `AGE`, `SEX`, `INCOME`)
-- VALUES ('Li', 'Junjie', 0, 1, 0);
-- 
-- INSERT INTO `TESTTABLE1`
-- (`ID`, `DATA`)
-- VALUES (2, 12331);
-- INSERT INTO `TESTTABLE1`
-- (`ID`, `DATA`)
-- VALUES (3, 1568);
-- INSERT INTO `TESTTABLE1`
-- (`ID`, `DATA`)
-- VALUES (4, 86);
-- INSERT INTO `TESTTABLE1`
-- (`ID`, `DATA`)
-- VALUES (5, 3786);
-- INSERT INTO `TESTTABLE1`
-- (`ID`, `DATA`)
-- VALUES (6, 7456456);

-- UPDATE `TESTTABLE` set
-- `INCOME` = 1
-- WHERE `INCOME` = 0;
-- 
SELECT `ID` FROM `TESTTABLE`;

-- DELETE FROM `TESTTABLE`
-- WHERE `ID` = 1;


SELECT `ID`,`INCOME` FROM `TESTTABLE` WHERE `SEX`=1 ORDER BY `INCOME` DESC;



-- DROP TABLE IF EXISTS `TESTTABLE1`;
-- DROP TABLE IF EXISTS `TESTTABLE`;
