USE `test`;
SELECT `ID`,`INCOME` FROM `TESTTABLE` WHERE `SEX`=1 ORDER BY `INCOME` DESC;
SELECT `SEX`,avg(`INCOME`) FROM `TESTTABLE` WHERE `INCOME` > (SELECT AVG(`INCOME`) FROM `TESTTABLE`) GROUP BY `SEX`;
SELECT `DATA` FROM `TESTTABLE1` WHERE `ID` IN (SELECT `ID` FROM `TESTTABLE` WHERE `INCOME` > (SELECT AVG(`INCOME`) FROM `TESTTABLE`));
SELECT `INCOME` FROM (SELECT * FROM `TESTTABLE` WHERE `AGE`<100) `t` WHERE `t`.`INCOME` > 100;


SELECT 
`ID`, `INCOME`, (
SELECT `DATA` from `TESTTABLE1` 
WHERE `TESTTABLE`.`ID`=`TESTTABLE1`.`ID`
) as `DATA` 
from `TESTTABLE` ORDER BY `INCOME`;

SELECT `t`.`ID`,`t`.`INCOME`,`t1`.`DATA` from (SELECT `ID`,`INCOME` from `TESTTABLE`) t
join (SELECT `ID`, `DATA` from `TESTTABLE1`) t1
on `t`.`ID`=`t1`.`ID`
ORDER BY `t`.`INCOME`;

SELECT `ID`, `DATA` from `TESTTABLE1`
UNION
SELECT `ID`, `INCOME` from `TESTTABLE`;

SELECT `ID` from `TESTTABLE1` WHERE `ID` NOT IN
(SELECT `INCOME` from `TESTTABLE`);

SELECT `ID` from `TESTTABLE1` WHERE `ID` IN
(SELECT `INCOME` from `TESTTABLE`);

SELECT `ID` from `TESTTABLE1` WHERE NOT EXISTS
(SELECT `INCOME` from `TESTTABLE` WHERE `TESTTABLE1`.`ID` = `TESTTABLE`.`INCOME`);

SELECT `ID` from `TESTTABLE1` WHERE EXISTS
(SELECT `INCOME` from `TESTTABLE` WHERE `TESTTABLE1`.`ID` = `TESTTABLE`.`INCOME`);

SELECT `INCOME`,(CASE WHEN `SEX`=0 THEN '女' ELSE '男' END) `SEX_han` FROM `TESTTABLE`;

SELECT `INCOME`,(CASE `SEX` WHEN 0 THEN '女' ELSE '男' END) `SEX_han` FROM `TESTTABLE`;

SELECT `INCOME`,IF(`SEX`=0,'女','男') `SEX_han` FROM `TESTTABLE`;

SELECT * from `TESTTABLE` WHERE `FIRST_NAME` LIKE "MaK %";
SELECT * from `TESTTABLE` WHERE `FIRST_NAME` LIKE "Ma_ %";

SELECT `AGE`, AVG(`INCOME`) FROM `TESTTABLE` GROUP BY `AGE` WITH ROLLUP HAVING AVG(`INCOME`) > 500 ORDER BY AVG(`INCOME`) DESC;

SELECT `AGE`, AVG(`INCOME`) as `avg_income`FROM `TESTTABLE` GROUP BY `AGE` HAVING `avg_income` > any(SELECT `INCOME` from `TESTTABLE` WHERE `AGE` > 1);
SELECT `AGE`, AVG(`INCOME`) as `avg_income`FROM `TESTTABLE` GROUP BY `AGE` HAVING `avg_income` > all(SELECT `INCOME` from `TESTTABLE` WHERE `AGE` > 1);

SELECT `AGE`, AVG(`INCOME`) FROM `TESTTABLE` GROUP BY `AGE` WITH ROLLUP HAVING AVG(`INCOME`) BETWEEN 100 AND 200;

SELECT `t1`.`AGE`, `t1`.`INCOME`, `t2`.`INCOME` FROM `TESTTABLE` as `t1`, `TESTTABLE` as `t2` WHERE `t1`.`AGE` = `t2`.`AGE` and `t1`.`INCOME` > `t2`.`INCOME`;

CREATE VIEW `younger` AS
SELECT * FROM `TESTTABLE` 
WHERE `AGE` < 30;

SELECT * FROM `younger`;

DROP VIEW IF EXISTS view_name;

SELECT NOW(), CURDATE(), CURTIME(), DATE(NOW()), DATE_FORMAT(NOW(), '%d %b %Y %T:%f');


